

CREATE TABLE `Y4BswmLq2r`.customers(
	Id VARCHAR(5) UNIQUE NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Address VARCHAR(60) NOT NULL,
	City VARCHAR(50) NOT NULL,
    Country VARCHAR(50) NOT NULL,
    PostalCode VARCHAR(15),
    Phone VARCHAR(20)
);